<!-- Start Footer -->
<footer id="footer" class="footer style-1 dark">
    <div class="row" style="margin-left: 0; margin-right: 0;">
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
            <a href="/" class="btn-scroll">
                <img style="height: 60px;" src="<?php echo $this->getSkinUrl('images/footer-logo-aliviet.png') ?>"
                     alt="#"
                     class="mr-auto img-responsive">
            </a>
            <ul>
                <li><a class="color"><i
                            class="ion-social-twitter"></i></a></li>
                <li><a href="https://www.facebook.com/orderaliviet/" target="_blank" class="color"><i
                            class="ion-social-facebook"></i></a>
                </li>
                <li><a class="color"><i
                            class="ion-social-linkedin"></i></a>
                </li>
                <li><a class="color"><i
                            class="ion-social-pinterest"></i></a>
                </li>
                <li><a class="color"><i
                            class="ion-social-googleplus"></i></a>
                </li>
            </ul>
            <strong>©
                Copyright AliViet 2015
            </strong>
        </div>
        <div class="col-md-4">
            <div class="fb-page fb_iframe_widget" data-href="https://www.facebook.com/orderaliviet/?fref=ts"
                 data-width="210"
                 data-height="215" data-small-header="true" data-adapt-container-width="true" data-hide-cover="false"
                 data-show-facepile="true" data-show-posts="true" fb-xfbml-state="rendered"
                 fb-iframe-plugin-query="adapt_container_width=true&amp;app_id=&amp;container_width=210&amp;height=215&amp;hide_cover=false&amp;href=https%3A%2F%2Fwww.facebook.com%2Forderaliviet%2F%3Ffref%3Dts&amp;locale=vi_VN&amp;sdk=joey&amp;show_facepile=true&amp;show_posts=true&amp;small_header=true&amp;width=210">
                <span style="vertical-align: bottom; width: 210px; height: 215px;">
                    <iframe name="f2e4bb074966be8" width="210px"
                            height="215px" frameborder="0"
                            allowtransparency="true"
                            allowfullscreen="true" scrolling="no"
                            title="fb:page Facebook Social Plugin"
                            src="https://www.facebook.com/v2.5/plugins/page.php?adapt_container_width=true&amp;app_id=&amp;channel=http%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter%2Fr%2FfTmIQU3LxvB.js%3Fversion%3D42%23cb%3Df1a96e0c595918%26domain%3Daliviet.vn%26origin%3Dhttp%253A%252F%252Faliviet.vn%252Ff359acab997b9f4%26relation%3Dparent.parent&amp;container_width=210&amp;height=215&amp;hide_cover=false&amp;href=https%3A%2F%2Fwww.facebook.com%2Forderaliviet%2F%3Ffref%3Dts&amp;locale=vi_VN&amp;sdk=joey&amp;show_facepile=true&amp;show_posts=true&amp;small_header=true&amp;width=210"
                            style="border: none; visibility: visible; width: 210px; height: 215px;"
                            class="">
                    </iframe>
                </span>
            </div>
            <!-- Back To Top Button -->
            <span><a class="scroll-top"><i class="ion-chevron-up"></i></a></span>
        </div>
    </div>
</footer>
<!-- End Footer -->
<script type="application/javascript" src="<?php echo $this->getSkinUrl('js/init.js'); ?>"></script>
<script type="application/javascript" src="<?php echo $this->getSkinUrl('js/scripts.js'); ?>"></script>
<?php if (Mage::getSingleton('customer/session')->isLoggedIn()):
    $name = Mage::getSingleton('customer/session')->getCustomer()->getName(); ?>
    <script>
        $j(document).ready(function(){
            $j('.signup').html('<a href="<?php echo $this->getUrl("customer/account") ?>"><span><?php echo $name ?></span></a>');
            $j('.signup').after('<li><a href="<?php echo $this->getUrl("customer/account/logout") ?>"><i class="fa fa-sign-out" style="font-size: 35px;"></i><span>Thoát</span></a></li>');
        })
    </script>
<?php endif; ?>
<div class="shopping-cart-popup" onclick="location.href='<?php echo $this->getUrl("checkout/cart") ?>'">
    <i class="fa fa-shopping-cart"></i>
    <span class="cart-count"><?php echo $this->helper('checkout/cart')->getSummaryCount() ? $this->helper('checkout/cart')->getSummaryCount() : 0 ?></span>
</div>