<div class="col-md-4">

    <header>
        <h3>Điều hướng</h3>

        <div class="gDot"></div>
    </header>
    <div class="panel-group mb0" id="accordion">
        <!-- First Panel -->
        <div class="panel panel-default">
            <div class="panel-heading">
                <button class="panel-title" data-toggle="collapse" data-target="#collapse1">
                    <h4 class="bold">Hướng dẫn</h4>
                </button>
            </div>
            <div id="collapse1" class="panel-collapse collapse open in">
                <div class="panel-body">
                    <ul>
                        <li><i class="fa fa-minus" aria-hidden="true"></i><a href="#" target="_blank"> Cài đặt công cụ</a></li>
                        <li><i class="fa fa-minus" aria-hidden="true"></i><a href="/bao-gia" target="_blank"> Biểu phí và dịch vụ</a></li>
                        <li><i class="fa fa-minus" aria-hidden="true"></i><a href="/gioi-thieu" target="_blank"> Ptite Shop là gì</a></li>
                        <li><i class="fa fa-minus" aria-hidden="true"></i><a> Hướng dẫn tìm hàng</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <!-- Second Panel -->
        <div class="panel panel-default">
            <div class="panel-heading">
                <button class="panel-title collapsed" data-toggle="collapse" data-target="#collapse2">
                    <h4 class="bold">Đặt hàng và quản lý đơn hàng</h4>
                </button>
            </div>
            <div id="collapse2" class="panel-collapse collapse">
                <div class="panel-body">
                    <ul>
                        <li><i class="fa fa-minus" aria-hidden="true"></i><a> Đặt hàng thông qua công cụ</a></li>
                        <li><i class="fa fa-minus" aria-hidden="true"></i><a> Đặt hàng thông qua form</a></li>
                        <li><i class="fa fa-minus" aria-hidden="true"></i><a> Quản lý và theo dõi đơn hàng</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <!-- Third Panel -->
        <div class="panel panel-default">
            <div class="panel-heading">
                <button class="panel-title collapsed" data-toggle="collapse" data-target="#collapse4">
                    <h4 class="bold">Quản lý tài khoản</h4>
                </button>
            </div>
            <div id="collapse4" class="panel-collapse collapse">
                <div class="panel-body">
                    <ul>
                        <li><i class="fa fa-minus" aria-hidden="true"></i><a href="http://portal.aliviet.vn/#/signUp" target="_blank"> Đăng kí tài khoản Ptite Shop</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

    </div>
    </div>
