<?php
/** @var ChickyDev_Homepageslider_Block_Slide $this */
$slides = $this->getSlides();
?>
<!-- Hero -->
<section id="hero" class="hero-fullscreen parallax" data-overlay-dark="2">
    <div class="background-image">
        <?php foreach ($slides as $slide) { ?>
            <img src="<?php echo $this->getUrl('media') . $slide->getImage() ?>">
        <?php } ?>
    </div>

    <div class="container">
        <div class="row">
            <div class="hero-content-slider mt20" data-autoplay="true" data-speed="3000">
                <?php foreach ($slides as $slide) { ?>
                <div class="col-sm-12 text-center">
                    <h2><strong><?php echo $slide->getTextlon() ?></strong></h2>

                    <p class="lead mb40"><?php echo $slide->getTextnho() ?></p>
                </div>
                <?php } ?>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 text-center">
                <a target="_blank"
                   href="#"
                   class="btn btn-lg btn-primary btn-scroll wrapper-icon-button">
                    <i class="fa fa-chrome icon-button"
                       aria-hidden="true"></i>
                    <span class="icon-button-text">
                             Đặt hàng
                        </span>
                </a>
                <a href="<?php echo $this->getUrl('customer/account/login') ?>" class="btn btn-lg btn-primary btn-scroll wrapper-icon-button">
                    <i class="fa fa-sign-in icon-button"
                       aria-hidden="true"></i>
                    <span class="icon-button-text">
                            Đăng nhập
                        </span>
                </a>
            </div>
            <div class="col-sm-12 text-center pt60">
                <a href="#shop" class="btn-scroll"
                   style="text-decoration: underline !important;color: white;font-size: 18px;font-weight: 600">Tìm hiểu
                    thêm <br/><i class="fa fa-angle-double-down"></i></a>
            </div>
        </div>
    </div>
    <a id="mute-toggle"><i class="ion-android-volume-mute"></i></a>
    <a id="play-toggle"><i class="ion-play"></i></a>
</section>
<!-- End Hero -->
