<!-- Hero -->
<section id="hero" class="hero-fullscreen parallax" data-overlay-dark="2">
    <div class="background-image">
        <video data-youtube-video-id="K9S9w17ecjw" id="vossen-youtube"></video>
    </div>

    <div class="container">
        <div class="row">
            <div class="hero-content-slider mt20" data-autoplay="true" data-speed="3000">
                <div class="col-sm-12 text-center">
                    <h2>Welcome To ALIVIET<br><strong>GIẢI PHÁP ĐẶT HÀNG TQ-VN </strong></h2>

                    <p class="lead mb40">"VÔ CÙNG NHANH"</p>
                </div>
                <div class="col-sm-12 text-center">
                    <h2><strong>TỰ HÀO LÀ DỊCH VỤ SỐ 1 VN</strong></h2>

                    <p class="lead mb40">"Uy tín - Chất lượng - Chính xác"</p>
                </div>
                <div class="col-sm-12 text-center">
                    <h2><strong>80% CÁC SHOP LỚN LỰA CHỌN CHÚNG TÔI</strong></h2>

                    <p class="lead mb40">"Mức giá cạnh tranh nhất thị trường"</p>
                </div>
                <div class="col-sm-12 text-center">
                    <h2><strong>HÀNG VỀ CHỈ 4-6 NGÀY</strong></h2>

                    <p class="lead mb40">"Mua hàng trong vòng 24h"</p>
                </div>
                <div class="col-sm-12 text-center">
                    <h2><strong>HỖ TRỢ TÌM HÀNG, TƯ VẤN KINH DOANH TẬN TÌNH</strong></h2>

                    <p class="lead mb40">"Nhiệt tình - Chăm chỉ - Mến khách"</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 text-center">
                <a target="_blank"
                   href="https://chrome.google.com/webstore/detail/c%C3%B4ng-c%E1%BB%A5-%C4%91%E1%BA%B7t-h%C3%A0ng-aliviet/jdpmgmhknjjonhlhajefkabnikhmjipd?utm_source=chrome-app-launcher-info-dialog"
                   class="btn btn-lg btn-primary btn-scroll wrapper-icon-button">
                    <i class="fa fa-chrome icon-button"
                       aria-hidden="true"></i>
                    <span class="icon-button-text">
                             Cài đặt công cụ
                        </span>
                </a>
                <a href="http://portal.aliviet.vn/#/signIn" class="btn btn-lg btn-primary btn-scroll wrapper-icon-button">
                    <i class="fa fa-sign-in icon-button"
                       aria-hidden="true"></i>
                    <span class="icon-button-text">
                            Đăng nhập
                        </span>
                </a>
            </div>
            <div class="col-sm-12 text-center pt60">
                <a href="#shop" class="btn-scroll"
                   style="text-decoration: underline !important;color: white;font-size: 18px;font-weight: 600">Tìm hiểu
                    thêm <br/><i class="fa fa-angle-double-down"></i></a>
            </div>
        </div>
    </div>
    <a id="mute-toggle"><i class="ion-android-volume-mute"></i></a>
    <a id="play-toggle"><i class="ion-play"></i></a>
</section>
<!-- End Hero -->
