<?php
/**
 * Shopping cart template
 *
 * @var $this Mage_Checkout_Block_Cart
 */
?>
<?php $info = Mage::helper('chickydev_remotecart')->getFeeInfo(); ?>
<?php $_priceDisplay = ($this->helper('tax')->displayCartBothPrices()) ? 'display-both-prices' : 'display-single-price'; ?>
<div class="shoppingcart cart <?php echo $_priceDisplay; ?>">
    <div class="page-title title-buttons">
        <h1><?php echo $this->__('Shopping Cart') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <?php echo $this->getChildHtml('form_before') ?>
    <form action="<?php echo $this->getFormActionUrl() ?>" method="post">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div class="ng-scope">
            <div style="margin-bottom: 50px" class="ng-scope">
                <div class="div-header">
                    <div class="checkRight">
                        <ul class="list-inline list-check-service padding-right-0">
                            <li>
                                <input type="checkbox" class="fee" name="muahang" value="1" disabled <?php echo isset($info['muahang']) ? 'checked' : '' ?> id="muahang">
                                <label class="checkbox-inline" for="muahang" title="Phí mua hàng(2%)">
                                    <span><i class="fa fa-shopping-cart"></i> Mua hàng</span>
                                </label>
                            </li>
                            <li>
                                <input type="checkbox" class="fee" name="kiemhang" value="1" <?php echo isset($info['kiemhang']) ? 'checked' : '' ?> id="kiemhang">
                                <label class="checkbox-inline" for="kiemhang" title="Phí kiểm hàng(1.5%)">
                                    <span><i class="fa fa-thumbs-up"></i> Kiểm hàng</span>
                                </label>
                            </li>
                            <li>
                                <input type="checkbox" class="fee" name="cpn" value="1" <?php echo isset($info['cpn']) ? 'checked' : '' ?> id="cpn">
                                <label class="checkbox-inline" for="cpn" title="Phí CPN(0%)">
                                    <span><i class="fa fa-rocket"></i> CPN</span>
                                </label>
                            </li>
                            <li>
                                <input type="checkbox" class="fee" name="donggo" value="1" <?php echo isset($info['donggo']) ? 'checked' : '' ?> id="donggo">
                                <label class="checkbox-inline" for="donggo" title="Phí đóng gỗ(0%)">
                                    <span><i class="fa fa-archive"></i> Đóng gỗ</span>
                                </label>
                            </li>
                            <li>
                                <input type="checkbox" class="fee" name="devo" value="1" <?php echo isset($info['devo']) ? 'checked' : '' ?> id="devo">
                                <label class="checkbox-inline" for="devo" title="Phí dễ vỡ(0%)">
                                    <span><i class="fa fa-glass"></i> Dễ vỡ</span>
                                </label>
                            </li>
                        </ul></div>
                </div>
                <div class="row div-content-product">
                    <div class="col-md-9 col-sm-12">
                        <table class="table-header-detailOrder">
                            <thead>
                            <tr>
                                <th style="width: 50%;">Sản phẩm</th>
                                <th style="width: 20%;">Số lượng</th>
                                <th style="width: 15%;">Đơn giá</th>
                                <th style="width: 15%;">Tiền hàng</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                            $items = $this->getItems();
                            foreach ($items as $item) {
                                $info = unserialize($item->getProduct()->getCustomOption('info_buyRequest')->getValue()); ?>
                            <tr class="ng-scope">
                                <td style="width: 50%">
                                    <div>
                                        <div class="div-img-product">
                                            <img src="<?php echo $info['image'] ?>">
                                        </div>
                                        <div class="div-infoProduct">
                                            <div class="tb-product-link" style="height: 30px;margin-bottom: 5px">
                                                <a style="color: #0b6198;" href="<?php echo $info['url'] ?>" target="_blank" title="<?php echo $info['url'] ?>"><?php echo $info['name'] ?></a>
                                            </div>
                                            <?php foreach ($info['option'] as $option): ?>
                                            <p><strong><?php echo $option['optionTitle'] ?>:</strong> <?php echo $option['optionValue'] ?></p>
                                            <?php endforeach ?>
                                        </div>
                                        <div>
                                            <input type="text" name="ghichu<?php echo $item->getId() ?>" value="<?php echo $info['ghichu'] ?>" class="form-control ghichu" rows="3" placeholder="Ghi chú (Nhấn Enter để lưu ghi chú)">
                                        </div>
                                    </div>

                                </td>
                                <td style="width: 20%" class="number-show-center">
                                    <!--<strong>{{item.quantity}}</strong>-->
                                    <input style="width: 100px;" type="number" name="cart[<?php echo $item->getId() ?>][qty]" value="<?php echo $item->getQty() ?>" />
                                </td>
                                <td style="width: 15%" class="number-show-center">
                                    <strong class="ng-binding"><?php echo number_format($item->getPrice()) ?><sup>đ</sup></strong><br>
                                    <span class="number-show ng-binding"><i class="fa fa-jpy"></i><?php echo number_format($info['price'], 2) ?>
                                        </span>
                                </td>
                                <td style="width: 15%" class="number-show-center">
                                    <strong class="ng-binding"><?php echo number_format($item->getRowTotal()) ?><sup>đ</sup>
                                    </strong><br>
                                    <span class="number-show ng-binding"><i class="fa fa-jpy"></i><?php echo number_format($info['price']*$item->getQty(), 2) ?>
                            </span>
                                </td>
                                <td>
                                    <a href="<?php echo $this->getUrl('checkout/cart/delete',array('id'=>$item->getId(),
                                            Mage_Core_Controller_Front_Action::PARAM_NAME_URL_ENCODED=>$this->helper('core/url')->getEncodedUrl())
                                    ) ?>" title="Xoá sản phẩm">
                                        <i class="fa fa-trash-o" style="font-size: 25px;padding: 10px 15px 10px 0px;"></i></a>
                                </td>
                            </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                        <div class="text-delete-order">
                            <a href="<?php echo $this->getUrl('remotecart/index/clear') ?>" onclick="return confirm('Bạn có chắc là muốn xóa sạch giỏ hàng không?')" style="color: #0b6198" class="ng-binding"><span class="fa fa-trash-o"></span> Xóa đơn hàng
                                (<?php echo $this->helper('checkout/cart')->getSummaryCount() ?> items)</a>
                            <input type="submit" class="updatecartbtn" value="Cập nhật giỏ hàng" />
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-12" style="padding-left: 0px">
                        <table class="payment-order-table">
                            <tbody>
                            <tr>
                                <td>Tiền hàng</td>
                                <td class="text-right">
                                    <div class="shop-total-price">
                                    <span class="ng-binding"><?php echo number_format($this->getQuote()->getSubtotal()) ?><sup>đ</sup>
                                    </span>
                                    </div>
                                </td>
                            </tr>
                            <tr style="border-bottom: 1px solid #ccc">
                                <td>
                                    <span class="popup-services">Phí tạm tính</span>
                                </td>
                                <td class="text-right">
                                    <div class="shop-total-price">
                                        <span class="ng-binding"><?php echo number_format($this->getQuote()->getFee()) ?><sup>đ</sup></span>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td><br>Tỉ giá hiện tại</td>
                                <td class="text-right"><br>

                                    <div class="shop-subtotal">
                                <span class="ng-binding"><?php echo Mage::getStoreConfig('remotecart/settings/rating') ?><sup> đ</sup>
                                </span>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td><br><strong>Tổng</strong></td>
                                <td class="text-right"><br>

                                    <div class="shop-total-price">
                                        <span style="color: red;font-size: 18px" class="ng-binding"><?php echo number_format($this->getQuote()->getGrandTotal()) ?><sup>đ</sup>
                                        </span>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2">
                                    <div class="note-wrap">
                                        <label for="comment-shop">Chọn kho hàng về</label>
                                        <select class="form-control" id="select-stock">
                                            <option label="Kho Hà Nội" value="HN" selected="selected">Kho Hà Nội</option>
                                            <option label="Kho Sài Gòn" value="SG">Kho Sài Gòn</option>
                                        </select>

                                    </div>
                                </td>
                            </tr>
                            <!--<tr>
                                <td colspan="2">
                                    <div class="note-wrap">
                                        <label for="comment-shop">Chú thích
                                            cho
                                            Ptite Shop</label></i>
                                        <textarea class="form-control" id="comment-shop" name="comment-shop" cols="12" rows="4" placeholder="Chú thích cho Ptiteshop về đơn hàng" style="margin: 0px 4.98438px 0px 0px; width: 100%; height: 94px;"></textarea>
                                    </div>
                                </td>
                            </tr>-->
                            <tr>
                                <td colspan="2" style="text-align: center; padding-left: 0">
                                    <a class="placeorderbtn">ĐẶT HÀNG</a>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<script>
    $j('.ghichu').on('keyup', function(e){
        var code = e.which;
        if(code==13) {
            e.preventDefault();
            $j.ajax({
                method: "post",
                url: "<?php echo $this->getUrl('remotecart/index/updateluuy') ?>",
                data: {id: $j(this).attr('name').replace('ghichu',''), value: $j(this).val()},
                success: function(data) {
                }
            });
        }
    });

    $j('.fee').on('change', function(){
        var state;
        if ($j(this).is(":checked")) {
            state = 1;
        } else {
            state = 0;
        }
        $j.ajax({
            method: "post",
            url: "<?php echo $this->getUrl('remotecart/index/updatequote') ?>",
            data: {id: $j(this).attr('name'), value: state},
            success: function(data) {
                location.reload();
            }
        });
    });

    $j('.placeorderbtn').on('click', function(e){
        e.preventDefault();
        $j.ajax({
            method: "get",
            url: "<?php echo $this->getUrl('remotecart/index/placeorder') ?>",
            success: function(data) {
                if (data == 'ok') {
                    location.href = "<?php echo $this->getUrl('checkout/onepage/success') ?>";
                }
            }
        });
    });
</script>