<?php $rememberMeId = 'remember_me' . Mage::helper('core')->getRandomString(10); ?>
<input type="checkbox" name="persistent_remember_me" class="checkbox" id="<?php echo $rememberMeId; ?>"<?php if ($this->isRememberMeChecked()): ?> checked="checked"<?php endif; ?> title="<?php echo $this->quoteEscape($this->__('Ghi nhớ')) ?>" />
<label for="<?php echo $rememberMeId; ?>"><?php echo $this->__('Ghi nhớ') ?></label>
