<!-- Start Header -->
<nav class="navbar nav-down menu-custom nav-small" data-fullwidth="true" data-menu-style="transparent" data-animation="shrink">
    <div class="container">
        <div class="navbar-header">
            <div class="container">
                <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#navbar"><span
                        class="sr-only">Toggle navigation</span> <span class="icon-bar top-bar"></span> <span
                        class="icon-bar middle-bar"></span> <span class="icon-bar bottom-bar"></span></button>
                <a class="navbar-brand to-top" href="/">
                    <img alt="#" class="logo-light" src="<?php echo $this->getLogoSrc() ?>" style="padding: 10px;"/>
                    <img alt="#" class="logo-dark" src="<?php echo $this->getLogoSrc() ?>" style="padding: 10px;"/>
                </a>
            </div>
        </div>
        <div class="navbar-collapse collapse" id="navbar">
            <div class="container" style="background-color: white;">
                <?php echo $this->getChildHtml('topMenu') ?>
            </div>
        </div>
    </div>
</nav>
<!-- End Header -->
<div class="pre-loader" style="opacity: 0; display: none;">
    <div></div>
</div>